# Use the AWS Lambda Python base image (Small & Optimized)
FROM public.ecr.aws/lambda/python:3.11

# Copy the lightweight production requirements
COPY requirements.txt ${LAMBDA_TASK_ROOT}

# Install ONNX Runtime (CPU version is small)
# use --no-cache-dir to keep the image slim
RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

# Copy the Inference Code (NOT the training code)
COPY src/app.py ${LAMBDA_TASK_ROOT}/src/
COPY src/features.py ${LAMBDA_TASK_ROOT}/src/

# Copy the Model and Scaler (These are generated by training pipeline)
COPY models/model.onnx ${LAMBDA_TASK_ROOT}/models/
COPY models/scaler.pkl ${LAMBDA_TASK_ROOT}/models/
COPY models/calibration_score.txt ${LAMBDA_TASK_ROOT}/models/

# Set the CMD to handler
CMD [ "src.app.handler" ]

# Force Rebuild: v2